#ifndef _PTRS_EMBED
#define _PTRS_EMBED

#include "../PointerScript/parser/ast.h"

#define PTRS_DISABLE_CONSTRESOLVE

void logParseError(ptrs_ast_t *pos, const char *msg, ...);
#define PTRS_HANDLE_ASTERROR(ast, ...) \
	logParseError(ast, __VA_ARGS__)

#define PTRS_HANDLE_BODY ((void*)1)
#define PTRS_HANDLE_DEFINE ((void*)1)
#define PTRS_HANDLE_ARRAY ((void*)1)
#define PTRS_HANDLE_VARARRAY ((void*)1)
#define PTRS_HANDLE_STRUCTVAR ((void*)1)
#define PTRS_HANDLE_IMPORT ((void*)1)
#define PTRS_HANDLE_RETURN ((void*)1)
#define PTRS_HANDLE_BREAK ((void*)1)
#define PTRS_HANDLE_CONTINUE ((void*)1)
#define PTRS_HANDLE_DELETE ((void*)1)
#define PTRS_HANDLE_THROW ((void*)1)
#define PTRS_HANDLE_TRYCATCH ((void*)1)
#define PTRS_HANDLE_FUNCTION ((void*)1)
#define PTRS_HANDLE_STRUCT ((void*)1)
#define PTRS_HANDLE_IF ((void*)1)
#define PTRS_HANDLE_WHILE ((void*)1)
#define PTRS_HANDLE_DOWHILE ((void*)1)
#define PTRS_HANDLE_FOR ((void*)1)
#define PTRS_HANDLE_FORIN ((void*)1)
#define PTRS_HANDLE_FILE ((void*)1)
#define PTRS_HANDLE_SCOPESTATEMENT ((void*)1)
#define PTRS_HANDLE_EXPRSTATEMENT ((void*)1)

#define PTRS_HANDLE_CALL ((void*)1)
#define PTRS_HANDLE_ARRAYEXPR ((void*)1)
#define PTRS_HANDLE_VARARRAYEXPR ((void*)1)
#define PTRS_HANDLE_STRINGFORMAT ((void*)1)
#define PTRS_HANDLE_NEW ((void*)1)
#define PTRS_HANDLE_MEMBER ((void*)1)
#define PTRS_HANDLE_INDEX ((void*)1)
#define PTRS_HANDLE_AS ((void*)1)
#define PTRS_HANDLE_CAST ((void*)1)
#define PTRS_HANDLE_IDENTIFIER ((void*)1)
#define PTRS_HANDLE_CONSTANT ((void *)2)

#define PTRS_HANDLE_OP_TERNARY ((void *)3)
#define PTRS_HANDLE_OP_INSTANCEOF ((void*)1)
#define PTRS_HANDLE_OP_EQUAL ((void*)1)
#define PTRS_HANDLE_OP_INEQUAL ((void*)1)
#define PTRS_HANDLE_OP_LESSEQUAL ((void*)1)
#define PTRS_HANDLE_OP_GREATEREQUAL ((void*)1)
#define PTRS_HANDLE_OP_LESS ((void*)1)
#define PTRS_HANDLE_OP_GREATER ((void*)1)
#define PTRS_HANDLE_OP_ASSIGN ((void*)1)
#define PTRS_HANDLE_OP_ADDASSIGN ((void*)1)
#define PTRS_HANDLE_OP_SUBASSIGN ((void*)1)
#define PTRS_HANDLE_OP_MULASSIGN ((void*)1)
#define PTRS_HANDLE_OP_DIVASSIGN ((void*)1)
#define PTRS_HANDLE_OP_MODASSIGN ((void*)1)
#define PTRS_HANDLE_OP_SHRASSIGN ((void*)1)
#define PTRS_HANDLE_OP_SHLASSIGN ((void*)1)
#define PTRS_HANDLE_OP_ANDASSIGN ((void*)1)
#define PTRS_HANDLE_OP_XORASSIGN ((void*)1)
#define PTRS_HANDLE_OP_ORASSIGN ((void*)1)
#define PTRS_HANDLE_OP_LOGICOR ((void*)1)
#define PTRS_HANDLE_OP_LOGICXOR ((void*)1)
#define PTRS_HANDLE_OP_LOGICAND ((void*)1)
#define PTRS_HANDLE_OP_OR ((void*)1)
#define PTRS_HANDLE_OP_XOR ((void*)1)
#define PTRS_HANDLE_OP_AND ((void*)1)
#define PTRS_HANDLE_OP_SHR ((void*)1)
#define PTRS_HANDLE_OP_SHL ((void*)1)
#define PTRS_HANDLE_OP_ADD ((void*)1)
#define PTRS_HANDLE_OP_SUB ((void*)1)
#define PTRS_HANDLE_OP_MUL ((void*)1)
#define PTRS_HANDLE_OP_DIV ((void*)1)
#define PTRS_HANDLE_OP_MOD ((void*)1)

#define PTRS_HANDLE_OP_TYPEOF ((void*)1)
#define PTRS_HANDLE_PREFIX_INC ((void*)1)
#define PTRS_HANDLE_PREFIX_DEC ((void*)1)
#define PTRS_HANDLE_PREFIX_LOGICNOT ((void*)1)
#define PTRS_HANDLE_PREFIX_NOT ((void*)1)
#define PTRS_HANDLE_PREFIX_LENGTH ((void*)1)
#define PTRS_HANDLE_PREFIX_ADDRESS ((void*)1)
#define PTRS_HANDLE_PREFIX_DEREFERENCE ((void*)1)
#define PTRS_HANDLE_PREFIX_PLUS ((void*)1)
#define PTRS_HANDLE_PREFIX_MINUS ((void*)1)

#define PTRS_HANDLE_SUFFIX_INC ((void*)1)
#define PTRS_HANDLE_SUFFIX_DEC ((void*)1)


#endif
