#ifndef _PTRS_EMBED
#define _PTRS_EMBED

#include "../PointerScript/parser/ast.h"

#define PTRS_DISABLE_CONSTRESOLVE

void logParseError(ptrs_ast_t *pos, const char *msg, ...);
#define PTRS_HANDLE_ASTERROR(ast, ...) \
	logParseError(ast, __VA_ARGS__)

#define PTRS_HANDLE_BODY NULL
#define PTRS_HANDLE_DEFINE NULL
#define PTRS_HANDLE_ARRAY NULL
#define PTRS_HANDLE_VARARRAY NULL
#define PTRS_HANDLE_IMPORT NULL
#define PTRS_HANDLE_RETURN NULL
#define PTRS_HANDLE_BREAK NULL
#define PTRS_HANDLE_CONTINUE NULL
#define PTRS_HANDLE_THROW NULL
#define PTRS_HANDLE_TRYCATCH NULL
#define PTRS_HANDLE_FUNCTION NULL
#define PTRS_HANDLE_STRUCT NULL
#define PTRS_HANDLE_IF NULL
#define PTRS_HANDLE_WHILE NULL
#define PTRS_HANDLE_DOWHILE NULL
#define PTRS_HANDLE_FOR NULL
#define PTRS_HANDLE_FORIN NULL
#define PTRS_HANDLE_SCOPESTATEMENT NULL
#define PTRS_HANDLE_EXPRSTATEMENT NULL

#define PTRS_HANDLE_CALL NULL
#define PTRS_HANDLE_ARRAYEXPR NULL
#define PTRS_HANDLE_VARARRAYEXPR NULL
#define PTRS_HANDLE_NEW NULL
#define PTRS_HANDLE_MEMBER NULL
#define PTRS_HANDLE_INDEX NULL
#define PTRS_HANDLE_CAST NULL
#define PTRS_HANDLE_IDENTIFIER NULL
#define PTRS_HANDLE_CONSTANT ((void *)1)

#define PTRS_HANDLE_OP_TERNARY ((void *)2)
#define PTRS_HANDLE_OP_EQUAL NULL
#define PTRS_HANDLE_OP_INEQUAL NULL
#define PTRS_HANDLE_OP_LESSEQUAL NULL
#define PTRS_HANDLE_OP_GREATEREQUAL NULL
#define PTRS_HANDLE_OP_LESS NULL
#define PTRS_HANDLE_OP_GREATER NULL
#define PTRS_HANDLE_OP_ASSIGN NULL
#define PTRS_HANDLE_OP_ADDASSIGN NULL
#define PTRS_HANDLE_OP_SUBASSIGN NULL
#define PTRS_HANDLE_OP_MULASSIGN NULL
#define PTRS_HANDLE_OP_DIVASSIGN NULL
#define PTRS_HANDLE_OP_MODASSIGN NULL
#define PTRS_HANDLE_OP_SHRASSIGN NULL
#define PTRS_HANDLE_OP_SHLASSIGN NULL
#define PTRS_HANDLE_OP_ANDASSIGN NULL
#define PTRS_HANDLE_OP_XORASSIGN NULL
#define PTRS_HANDLE_OP_ORASSIGN NULL
#define PTRS_HANDLE_OP_LOGICOR NULL
#define PTRS_HANDLE_OP_LOGICAND NULL
#define PTRS_HANDLE_OP_OR NULL
#define PTRS_HANDLE_OP_XOR NULL
#define PTRS_HANDLE_OP_AND NULL
#define PTRS_HANDLE_OP_SHR NULL
#define PTRS_HANDLE_OP_SHL NULL
#define PTRS_HANDLE_OP_ADD NULL
#define PTRS_HANDLE_OP_SUB NULL
#define PTRS_HANDLE_OP_MUL NULL
#define PTRS_HANDLE_OP_DIV NULL
#define PTRS_HANDLE_OP_MOD NULL

#define PTRS_HANDLE_OP_TYPEOF NULL
#define PTRS_HANDLE_PREFIX_INC NULL
#define PTRS_HANDLE_PREFIX_DEC NULL
#define PTRS_HANDLE_PREFIX_LOGICNOT NULL
#define PTRS_HANDLE_PREFIX_NOT NULL
#define PTRS_HANDLE_PREFIX_ADDRESS NULL
#define PTRS_HANDLE_PREFIX_DEREFERENCE NULL
#define PTRS_HANDLE_PREFIX_PLUS NULL
#define PTRS_HANDLE_PREFIX_MINUS NULL

#define PTRS_HANDLE_SUFFIX_INC NULL
#define PTRS_HANDLE_SUFFIX_DEC NULL


#endif
